### ISSUE TITLE
I get an endless loading learn symbol 

### ISSUE THREAD

**Issue by ruthmesfun** [learn-co-curriculum/python-practice-with-datatypes#5]
<img width="1153" alt="screen shot 2018-04-07 at 1 49 32 pm" src="https://user-images.githubusercontent.com/11494166/38473577-33faf29a-3b60-11e8-8ec5-0e98f30cba25.png">

**Comment by PellBlu** [comment]
You can access the materials by opening them on Github via the Github icon to the right of the title.
